author: อารักขาข้าว
description: My personal website and blog about data analysis, applied statistics, R
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title.html
markdown: kramdown
exclude: ["Rmd", ".DS_Store", "README.md"]
excerpt_separator: <!--more-->
